### ISSUE TITLE
Error running timer after update of lsp-docker to latest commit

### ISSUE THREAD

**Issue by dmrauh** [emacs-lsp/lsp-docker#32]
**Describe the Bug**

`lsp-docker` became unusable for me after the changes introduced by commit c94531fa5bf1b4d30556e692e8b89b836f1d9910 yielding the following error message in \*Messages*: Error running timer: (user-error "The path /home/dmrauh/Code is not under path mappings") after starting `doom-emacs` and opening a Python file.

**To Reproduce**

- Use this configuration as part of a private config in `doom-emacs`
```elisp
(load! "lsp-docker/lsp-docker")

(use-package! lsp-docker
  :after lsp-mode
  :config
  (setq lsp-docker-client-packages
        '(lsp-bash lsp-pyls))

  (setq lsp-docker-client-configs
        (list
         (list :server-id 'bash-ls :docker-server-id 'bashls-docker :server-command "bash-language-server start")
         (list :server-id 'pyls :docker-server-id 'pyls-docker :server-command "pyls")))

  (setq lsp-docker-path-mappings
        `((,(file-truename "~/Code") . "/Code")))

  (lsp-docker-init-clients
   :client-packages lsp-docker-client-packages
   :client-configs lsp-docker-client-configs
   :path-mappings lsp-docker-path-mappings))
```
- Start `doom-emacs`
- Open a Python file located in `~/Code`

**Expected Behavior**
`lsp-docker` starting `pyls` in a docker container using the paths provided by `path-mappings`

Going back to the second to last commit by issuing `git checkout HEAD~1` in the `lsp-docker` project directory makes everything work as expected again.

**Comment by yyoncho** [comment]
I reverted https://github.com/emacs-lsp/lsp-docker/pull/31 till we find a better solution with @rnikoopour

**Comment by dmrauh** [comment]
Thanks @yyoncho I'm really looking forward to it! Keep up the great work!
