### ISSUE TITLE
yyoncho/lsp-emacs-docker docker images in quite big

### ISSUE THREAD

**Issue by hus787** [emacs-lsp/lsp-docker#4]
The current image stands 4.3GB which I quite big.

## Expected result

Docker image size of `yyoncho/lsp-emacs-docker`  to be < 100MB

**Comment by rnikoopour** [comment]
hi @hus787 

I don't think it's possible to get a container image that small.  

With the most recent set of changes the language server only container is compressed to 1.31GB.  

The container that has emacs + language servers is compressed to 1.53GB.
