### ISSUE TITLE
docker build fails with `/lsp-docker-langservers/Dockerfile`

### ISSUE THREAD

**Issue by hotoku** [emacs-lsp/lsp-docker#44]
I run the following command in `/lsp-docker-langserver`:

```
docker build -t hotoku/lsp-docker-langservers .
```

This results in failure. The log will be in the comment.

**Comment by hotoku** [comment]
[docker.log](https://github.com/emacs-lsp/lsp-docker/files/6719388/docker.log)
this is the log

**Comment by hotoku** [comment]
```
cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$PWD/clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04
```
The cause of error is this line.

**Comment by yyoncho** [comment]
FYI we will switch to the following docker image - https://github.com/emacs-lsp/lsp-gitpod/blob/master/pgtk/Dockerfile . The server installation will happen using `(lsp-ensure-server ...)` calls.

**Comment by hotoku** [comment]
Thank you. I will try it.

**Comment by hotoku** [comment]
When I reported this issue, I run the `docker build` in Mac OS Big Sur on Apple M1 tip. Now I tried to build it in Mac OS Catallina on Intel tip, and it succeeded. The failure seems to be because of my environment not the source code of the repository.
So I close this issue. Sorry to bother you.
