### ISSUE TITLE
DAP: debug server support

### ISSUE THREAD

**Issue by sfavazza** [emacs-lsp/lsp-docker#80]
When consulting the dap-mode official page, `lsp-docker` is mentioned as solution to dockerize a [debug servers](https://github.com/emacs-lsp/dap-mode/blob/096070aacff875a09c13e596e5d60a55e0f07ab1/README.org?plain=1#L67).

Though in the source code I cannot find any mention of the `debug` keyword. Is the support being dropped or never been there?

**Comment by factyy** [comment]
No, not like that: since `dap-mode` is a single package (instead of split `lsp-mode` and `lsp-docker`) all the docker-related functionality is there

**Comment by factyy** [comment]
Closed the issue since it has to be in `dap-mode` repo, just open a new one there
